token: 1111111111:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
whitelist:  # telegram user IDs
- 123456
- 9999

# Send notifications about executed commands to the specified user/group/channel.
# Set to null to disable notifications
notify_cid: 123456
